language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install: composer self-update

install: composer install -n

script:
  - vendor/bin/phpunit -v --exclude-group functional --coverage-clover=coverage.xml

#after_script:
#  - sh -c 'if [ $(phpenv version-name) = "7.2" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi;'

after_success:
  - bash <(curl -s https://codecov.io/bash)
