<?php

/*
 * This file is part of the phlexible package.
 *
 * (c) Stephan Wentz <sw@brainbits.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Phlexible\Component\MediaCache\Queue;

use Doctrine\Common\Collections\ArrayCollection;
use Phlexible\Bundle\MediaCacheBundle\Entity\CacheItem;

/**
 * Queue holds all cache items generated by a batch.
 *
 * @author Stephan Wentz <sw@brainbits.net>
 */
class Queue implements \Countable
{
    /**
     * @var CacheItem[]|ArrayCollection
     */
    private $items;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    /**
     * @param CacheItem $item
     *
     * @return $this
     */
    public function add(CacheItem $item)
    {
        if (!$this->items->contains($item)) {
            $this->items->add($item);
        }

        return $this;
    }

    /**
     * @param CacheItem $item
     *
     * @return $this
     */
    public function remove(CacheItem $item)
    {
        if ($this->items->contains($item)) {
            $this->items->removeElement($item);
        }

        return $this;
    }

    /**
     * @return CacheItem
     */
    public function first()
    {
        return $this->items->first();
    }

    /**
     * @return CacheItem[]
     */
    public function all()
    {
        return $this->items->getValues();
    }

    /**
     * @param Queue $queue
     *
     * @return $this
     */
    public function merge(Queue $queue)
    {
        foreach ($queue->all() as $queueItem) {
            $this->add($queueItem);
        }

        return $this;
    }

    /**
     * @return int
     */
    public function count()
    {
        return $this->items->count();
    }
}
