<?php

/*
 * This file is part of the phlexible package.
 *
 * (c) Stephan Wentz <sw@brainbits.net>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Phlexible\Component\Mime\Adapter;

use Phlexible\Component\Mime\Exception\DetectionFailedException;
use Phlexible\Component\Mime\Exception\FileNotFoundException;
use Phlexible\Component\Mime\Exception\NotAFileException;

/**
 * Internet media type detector extension adapter
 *
 * @author Stephan Wentz <swentz@brainbits.net>
 */
class ExtensionAdapter implements AdapterInterface
{
    private $internetMediaTypes = [
        // well known

        // text
        'txt'       => 'text/plain',
        'ini'       => 'text/plain',
        'css'       => 'text/css',
        'csv'       => 'text/csv',
        'js'        => 'application/x-javascript',
        'xml'       => 'text/xml',
        'rtf'       => 'application/rtf',
        // image
        'gif'       => 'image/gif',
        'jpeg'      => 'image/jpeg',
        'jpg'       => 'image/jpeg',
        'png'       => 'image/png',
        'tif'       => 'image/tiff',
        'tiff'      => 'image/tiff',
        'bmp'       => 'image/bmp',
        'ppm'       => 'image/x-portable-pixmap',
        'svg'       => 'image/svg',
        // image document
        'ai'        => 'application/postscript',
        'ps'        => 'application/postscript',
        'eps'       => 'application/postscript',
        'psd'       => 'image/x-photoshop',
        // flash
        'swf'       => 'application/x-shockwave-flash',
        // archive
        'zip'       => 'application/x-zip',
        'rar'       => 'application/x-rar-compressed',
        '7z'        => 'application/application/x-7z-compressed',
        // pdf
        'pdf'       => 'application/pdf',
        // audio
        'wma'       => 'audio/x-ms-wma',
        'mp3'       => 'audio/mpeg',
        'wav'       => 'audio/x-wav',
        'mid'       => 'audio/midi',
        'midi'      => 'audio/midi',
        // video
        'avi'       => 'video/x-msvideo',
        'mov'       => 'video/quicktime',
        'flv'       => 'video/x-flv',
        'f4v'       => 'video/mp4',
        'mp4'       => 'video/mp4',
        'mpeg'      => 'video/mpeg',
        'mpg'       => 'video/mpeg',
        'asf'       => 'video/x-ms-asf',
        'wmv'       => 'video/x-ms-wmv',
        'rm'        => 'application/vnd.rn-realmedia',
        // office
        'doc'       => 'application/msword',
        'docm'      => 'application/vnd.ms-word.document.macroEnabled.12',
        'docx'      => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'dot'       => 'application/msword',
        'dotm'      => 'application/vnd.ms-word.template.macroEnabled.12',
        'dotx'      => 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
        'xla'       => 'application/vnd.ms-excel',
        'xlam'      => 'application/vnd.ms-excel.addin.macroEnabled.12',
        'xlc'       => 'application/vnd.ms-excel',
        'xlm'       => 'application/vnd.ms-excel',
        'xls'       => 'application/vnd.ms-excel',
        'xlsb'      => 'application/vnd.ms-excel.sheet.binary.macroEnabled.12',
        'xlsm'      => 'application/vnd.ms-excel.sheet.macroEnabled.12',
        'xlsx'      => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'xlt'       => 'application/vnd.ms-excel',
        'xltm'      => 'application/vnd.ms-excel.template.macroEnabled.12',
        'xltx'      => 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
        'xlw'       => 'application/vnd.ms-excel',
        'pot'       => 'application/vnd.ms-powerpoint',
        'potm'      => 'application/vnd.ms-powerpoint.template.macroEnabled.12',
        'potx'      => 'application/vnd.openxmlformats-officedocument.presentationml.template',
        'ppam'      => 'application/vnd.ms-powerpoint.addin.macroEnabled.12',
        'pps'       => 'application/vnd.ms-powerpoint',
        'ppsm'      => 'application/vnd.ms-powerpoint.slideshow.macroEnabled.12',
        'ppt'       => 'application/vnd.ms-powerpoint',
        'pptm'      => 'application/vnd.ms-powerpoint.presentation.macroEnabled.12',
        'pptx'      => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        // openoffice
        'odt'       => 'application/vnd.oasis.opendocument.text',
        'ott'       => 'application/vnd.oasis.opendocument.text-template',
        'oth'       => 'application/vnd.oasis.opendocument.text-web',
        'odm'       => 'application/vnd.oasis.opendocument.text-master',
        'ods'       => 'application/vnd.oasis.opendocument.spreadsheet',
        'ots'       => 'application/vnd.oasis.opendocument.spreadsheet-template',
        'odp'       => 'application/vnd.oasis.opendocument.presentation',
        'otp'       => 'application/vnd.oasis.opendocument.presentation-template',
        'odg'       => 'application/vnd.oasis.opendocument.graphics',
        'otg'       => 'application/vnd.oasis.opendocument.graphics-template',
        'odc'       => 'application/vnd.oasis.opendocument.chart',
        'odf'       => 'application/vnd.oasis.opendocument.formula',
        'odb'       => 'application/vnd.oasis.opendocument.database',
        'odi'       => 'application/vnd.oasis.opendocument.image',
        // mindmap
        'mmap'      => 'application/vnd.mindjet.mindmanager',
        // other

        '3dm'       => 'x-world/x-3dmf',
        '3dmf'      => 'x-world/x-3dmf',
        'a'         => 'application/octet-stream',
        'aab'       => 'application/x-authorware-bin',
        'aam'       => 'application/x-authorware-map',
        'aas'       => 'application/x-authorware-seg',
        'abc'       => 'text/vnd.abc',
        'acgi'      => 'text/html',
        'afl'       => 'video/animaflex',
        'aif'       => 'audio/x-aiff',
        'aifc'      => 'audio/x-aiff',
        'aiff'      => 'audio/x-aiff',
        'aim'       => 'application/x-aim',
        'aip'       => 'text/x-audiosoft-intra',
        'ani'       => 'application/x-navi-animation',
        'aos'       => 'application/x-nokia-9000-communicator-add-on-software',
        'aps'       => 'application/mime',
        'arc'       => 'application/octet-stream',
        'arj'       => 'application/octet-stream',
        'art'       => 'image/x-jg',
        'asm'       => 'text/x-asm',
        'asp'       => 'text/asp',
        'asx'       => 'application/x-mplayer2',
        'au'        => 'audio/x-au',
        'avs'       => 'video/avs-video',
        'bcpio'     => 'application/x-bcpio',
        'bin'       => 'application/octet-stream',
        'bm'        => 'image/bmp',
        'boo'       => 'application/book',
        'book'      => 'application/book',
        'boz'       => 'application/x-bzip2',
        'bsh'       => 'application/x-bsh',
        'bz'        => 'application/x-bzip',
        'bz2'       => 'application/x-bzip2',
        'c'         => 'text/plain',
        'c++'       => 'text/plain',
        'cab'       => 'application/cab ',
        'cat'       => 'application/vnd.ms-pki.seccat',
        'cc'        => 'text/plain',
        'ccad'      => 'application/clariscad',
        'cco'       => 'application/x-cocoa',
        'cdf'       => 'application/x-cdf',
        'class'     => 'application/x-java-class',
        'com'       => 'application/octet-stream',
        'conf'      => 'text/plain',
        'cpio'      => 'application/x-cpio',
        'cpp'       => 'text/x-c',
        'cpt'       => 'application/x-compactpro',
        'crl'       => 'application/pkcs-crl',
        'crt'       => 'application/x-x509-ca-cert',
        'csh'       => 'application/x-csh',
        'cxx'       => 'text/plain',
        'dcr'       => 'application/x-director',
        'deepv'     => 'application/x-deepv',
        'def'       => 'text/plain',
        'der'       => 'application/x-x509-ca-cert',
        'dif'       => 'video/x-dv',
        'dir'       => 'application/x-director',
        'dl'        => 'video/x-dl',
        'dp'        => 'application/commonground',
        'drw'       => 'application/drafting',
        'dump'      => 'application/octet-stream',
        'dv'        => 'video/x-dv',
        'dvi'       => 'application/x-dvi',
        'dwf'       => 'drawing/x-dwf',
        'dwg'       => 'application/acad',
        'dxf'       => 'application/dxf',
        'dxr'       => 'application/x-director',
        'el'        => 'text/x-script.elisp',
        'elc'       => 'application/x-bytecode.elisp',
        'env'       => 'application/x-envoy',
        'es'        => 'application/x-esrehber',
        'etx'       => 'text/x-setext',
        'evy'       => 'application/x-envoy',
        'exe'       => 'application/octet-stream',
        'f'         => 'text/x-fortran',
        'f77'       => 'text/x-fortran',
        'f90'       => 'text/x-fortran',
        'fdf'       => 'application/vnd.fdf',
        'fif'       => 'image/fif',
        'fli'       => 'video/fli',
        'flo'       => 'image/florian',
        'flx'       => 'text/vnd.fmi.flexstor',
        'fmf'       => 'video/x-atomic3d-feature',
        'for'       => 'text/x-fortran',
        'fpx'       => 'image/vnd.fpx',
        'frl'       => 'application/freeloader',
        'funk'      => 'audio/make',
        'g'         => 'text/plain',
        'g3'        => 'image/g3fax',
        'gl'        => 'video/gl',
        'gsd'       => 'audio/x-gsm',
        'gsm'       => 'audio/x-gsm',
        'gsp'       => 'application/x-gsp',
        'gss'       => 'application/x-gss',
        'gtar'      => 'application/x-gtar',
        'gz'        => 'application/x-gzip',
        'h'         => 'text/x-h',
        'hdf'       => 'application/x-hdf',
        'help'      => 'application/x-helpfile',
        'hgl'       => 'application/vnd.hp-hpgl',
        'hh'        => 'text/x-h',
        'hlp'       => 'application/x-helpfile',
        'hpg'       => 'application/vnd.hp-hpgl',
        'hpgl'      => 'application/vnd.hp-hpgl',
        'hqx'       => 'application/binhex',
        'hta'       => 'application/hta',
        'htc'       => 'text/x-component',
        'htm'       => 'text/html',
        'html'      => 'text/html',
        'htmls'     => 'text/html',
        'htt'       => 'text/webviewhtml',
        'ico'       => 'image/x-icon',
        'idc'       => 'text/plain',
        'ief'       => 'image/ief',
        'iefs'      => 'image/ief',
        'iges'      => 'application/iges',
        'igs'       => 'model/iges',
        'ima'       => 'application/x-ima',
        'imap'      => 'application/x-httpd-imap',
        'ins'       => 'application/x-internett-signup',
        'isu'       => 'video/x-isvideo',
        'it'        => 'audio/it',
        'iv'        => 'application/x-inventor',
        'ivr'       => 'i-world/i-vrml',
        'ivy'       => 'application/x-livescreen',
        'jav'       => 'text/x-java-source',
        'java'      => 'text/plain',
        'jfif'      => 'image/jpeg',
        'jfif-tbnl' => 'image/jpeg',
        'jpe'       => 'image/jpeg',
        'jps'       => 'image/x-jps',
        'jut'       => 'image/jutvision',
        'kar'       => 'music/x-karaoke',
        'ksh'       => 'text/x-script.ksh',
        'lam'       => 'audio/x-liveaudio',
        'lha'       => 'application/lha',
        'list'      => 'text/plain',
        'lma'       => 'audio/x-nspaudio',
        'lsx'       => 'text/x-la-asf',
        'ltx'       => 'application/x-latex',
        'lzh'       => 'application/x-lzh',
        'lzx'       => 'application/lzx',
        'm'         => 'text/x-m',
        'm1v'       => 'video/mpeg',
        'm2a'       => 'audio/mpeg',
        'm2v'       => 'video/mpeg',
        'man'       => 'application/x-troff-man',
        'map'       => 'application/x-navimap',
        'mar'       => 'text/plain',
        'mbd'       => 'application/mbedlet',
        'mc$'       => 'application/x-magic-cap-package-1.0',
        'mcd'       => 'application/mcad',
        'mcf'       => 'image/vasa',
        'mcp'       => 'application/netmc',
        'mht'       => 'message/rfc822',
        'mhtml'     => 'message/rfc822',
        'mif'       => 'application/x-mif',
        'mjf'       => 'audio/x-vnd.audioexplosion.mjuicemediafile',
        'mm'        => 'application/base64',
        'mme'       => 'application/base64',
        'mod'       => 'audio/mod',
        'moov'      => 'video/quicktime',
        'movie'     => 'video/x-sgi-movie',
        'mp2'       => 'audio/x-mpeg',
        'mpa'       => 'audio/mpeg',
        'mpc'       => 'application/x-project',
        'mpe'       => 'video/mpeg',
        'mpga'      => 'audio/mpeg',
        'mpp'       => 'application/vnd.ms-project',
        'mpt'       => 'application/x-project',
        'mpv'       => 'application/x-project',
        'mpx'       => 'application/x-project',
        'mrc'       => 'application/marc',
        'ms'        => 'application/x-troff-ms',
        'mv'        => 'video/x-sgi-movie',
        'my'        => 'audio/make',
        'mzz'       => 'application/x-vnd.audioexplosion.mzz',
        'nap'       => 'image/naplps',
        'naplps'    => 'image/naplps',
        'nc'        => 'application/x-netcdf',
        'ncm'       => 'application/vnd.nokia.configuration-message',
        'nif'       => 'image/x-niff',
        'niff'      => 'image/x-niff',
        'nix'       => 'application/x-mix-transfer',
        'nsc'       => 'application/x-conference',
        'nvd'       => 'application/x-navidoc',
        'o'         => 'application/octet-stream',
        'oda'       => 'application/oda',
        'omc'       => 'application/x-omc',
        'omcd'      => 'application/x-omcdatamaker',
        'omcr'      => 'application/x-omcregerator',
        'p'         => 'text/x-pascal',
        'p10'       => 'application/pkcs10',
        'p12'       => 'application/pkcs-12',
        'p7a'       => 'application/x-pkcs7-signature',
        'p7c'       => 'application/pkcs7-mime',
        'p7m'       => 'application/pkcs7-mime',
        'p7r'       => 'application/x-pkcs7-certreqresp',
        'p7s'       => 'application/pkcs7-signature',
        'pas'       => 'text/pascal',
        'pcl'       => 'application/vnd.hp-pcl',
        'pct'       => 'image/x-pict',
        'pcx'       => 'image/x-pcx',
        'pdb'       => 'chemical/x-pdb',
        'pfunk'     => 'audio/make',
        'pgm'       => 'image/x-portable-graymap',
        'php'       => 'text/php',
        'pic'       => 'image/pict',
        'pict'      => 'image/pict',
        'pkg'       => 'application/x-newton-compatible-pkg',
        'pko'       => 'application/vnd.ms-pki.pko',
        'pl'        => 'text/x-script.perl',
        'plx'       => 'application/x-pixclscript',
        'pm'        => 'text/x-script.perl-module',
        'pm5'       => 'application/x-pagemaker',
        'pnm'       => 'application/x-portable-anymap',
        'pov'       => 'model/x-pov',
        'pre'       => 'application/x-freelance',
        'prt'       => 'application/pro_eng',
        'pvu'       => 'paleovu/x-pv',
        'qif'       => 'image/x-quicktime',
        'qt'        => 'video/quicktime',
        'qtc'       => 'video/x-qtc',
        'qti'       => 'image/x-quicktime',
        'qtif'      => 'image/x-quicktime',
        'ra'        => 'audio/x-pn-realaudio',
        'ram'       => 'audio/x-pn-realaudio',
        'ras'       => 'application/x-cmu-raster',
        'rast'      => 'image/cmu-raster',
        'rf'        => 'image/vnd.rn-realflash',
        'rmi'       => 'audio/mid',
        'rmp'       => 'audio/x-pn-realaudio',
        'rng'       => 'application/vnd.nokia.ringing-tone',
        'roff'      => 'application/x-troff',
        'rpm'       => 'audio/x-pn-realaudio-plugin',
        'rt'        => 'text/richtext',
        'rtx'       => 'application/rtf',
        'rv'        => 'video/vnd.rn-realvideo',
        's'         => 'text/x-asm',
        'saveme'    => 'application/octet-stream',
        'scm'       => 'video/x-scm',
        'sdml'      => 'text/plain',
        'sdr'       => 'application/sounder',
        'sea'       => 'application/sea',
        'set'       => 'application/set',
        'sgml'      => 'text/sgml',
        'sh'        => 'application/x-bsh',
        'shar'      => 'application/x-shar',
        'shtml'     => 'text/x-server-parsed-html',
        'sid'       => 'audio/x-psid',
        'sit'       => 'application/x-sit',
        'skd'       => 'application/x-koan',
        'snd'       => 'audio/x-adpcm',
        'sol'       => 'application/solids',
        'spl'       => 'application/futuresplash',
        'spr'       => 'application/x-sprite',
        'src'       => 'application/x-wais-source',
        'ssi'       => 'text/x-server-parsed-html',
        'sst'       => 'application/vnd.ms-pki.certstore',
        'step'      => 'application/step',
        'stl'       => 'application/vnd.ms-pki.stl',
        'stp'       => 'application/step',
        'sv4cpio'   => 'application/x-sv4cpio',
        'sv4crc'    => 'application/x-sv4crc',
        'svf'       => 'image/vnd.dwg',
        'svr'       => 'application/x-world',
        't'         => 'application/x-troff',
        'talk'      => 'text/x-speech',
        'tar'       => 'application/x-tar',
        'tbk'       => 'application/toolbook',
        'tcl'       => 'text/x-script.tcl',
        'tcsh'      => 'text/x-script.tcsh',
        'tex'       => 'application/x-tex',
        'texi'      => 'application/x-texinfo',
        'texinfo'   => 'application/x-texinfo',
        'text'      => 'text/plain',
        'tgz'       => 'application/gnutar',
        'tr'        => 'application/x-troff',
        'tsi'       => 'audio/tsp-audio',
        'tsp'       => 'audio/tsplayer',
        'tsv'       => 'text/tab-separated-values',
        'turbot'    => 'image/florian',
        'uil'       => 'text/x-uil',
        'uni'       => 'text/uri-list',
        'unis'      => 'text/uri-list',
        'unv'       => 'application/i-deas',
        'uri'       => 'text/uri-list',
        'uris'      => 'text/uri-list',
        'ustar'     => 'application/x-ustar',
        'uu'        => 'text/x-uuencode',
        'uue'       => 'text/x-uuencode',
        'vcd'       => 'application/x-cdlink',
        'vcs'       => 'text/x-vcalendar',
        'vda'       => 'application/vda',
        'vdo'       => 'video/vdo',
        'viv'       => 'video/vnd.vivo',
        'vivo'      => 'video/vnd.vivo',
        'vmf'       => 'application/vocaltec-media-file',
        'voc'       => 'audio/voc',
        'vos'       => 'video/vosaic',
        'vox'       => 'audio/voxware',
        'vqe'       => 'audio/x-twinvq-plugin',
        'vqf'       => 'audio/x-twinvq',
        'vrml'      => 'application/x-vrml',
        'vrt'       => 'x-world/x-vrt',
        'vsd'       => 'application/x-visio',
        'vst'       => 'application/x-visio',
        'w60'       => 'application/wordperfect6.0',
        'w61'       => 'application/wordperfect6.1',
        'w6w'       => 'application/msword',
        'wb1'       => 'application/x-qpro',
        'wbmp'      => 'image/vnd.wap.wbmp',
        'web'       => 'application/vnd.xara',
        'wiz'       => 'application/msword',
        'wk1'       => 'application/x-123',
        'wmf'       => 'windows/metafile',
        'wml'       => 'text/vnd.wap.wml',
        'wmls'      => 'text/vnd.wap.wmlscript',
        'wp'        => 'application/wordperfect',
        'wp5'       => 'application/wordperfect',
        'wpd'       => 'application/wordperfect',
        'wq1'       => 'application/x-lotus',
        'wri'       => 'application/mswrite',
        'wrl'       => 'model/vrml',
        'wrz'       => 'model/vrml',
        'wsc'       => 'text/scriplet',
        'wsrc'      => 'application/x-wais-source',
        'xbm'       => 'image/xbm',
        'xdr'       => 'video/x-amt-demorun',
        'xgz'       => 'xgl/drawing',
        'xif'       => 'image/vnd.xiff',
        'xl'        => 'application/excel',
        'xlb'       => 'application/excel',
        'xlk'       => 'application/excel',
        'xll'       => 'application/excel',
        'xm'        => 'audio/xm',
        'xmz'       => 'xgl/movie',
        'xpix'      => 'application/x-vnd.ls-xpix',
        'xpm'       => 'image/xpm',
        'x-png'     => 'image/png',
        'xsr'       => 'video/x-amt-showrun',
        'xwd'       => 'image/x-xwd',
        'xyz'       => 'chemical/x-pdb',
        'z'         => 'application/x-compressed',
        'zoo'       => 'application/octet-stream',
        'zsh'       => 'text/x-script.zsh'
    ];

    /**
     * {@inheritdoc}
     */
    public function isAvailable($filename)
    {
        return pathinfo($filename, PATHINFO_EXTENSION) !== '';
    }

    /**
     * {@inheritdoc}
     */
    public function getInternetMediaTypeStringFromFile($filename)
    {
        if (!file_exists($filename)) {
            throw new FileNotFoundException('File "' . $filename . '" not found.');
        }

        if (!is_file($filename)) {
            throw new NotAFileException('File "' . $filename . '" not found.');
        }

        $pos = strrpos(basename($filename), '.');

        if ($pos !== false) {
            $extension = strtolower(substr(basename($filename), $pos + 1));

            if (array_key_exists($extension, $this->internetMediaTypes)) {
                return $this->internetMediaTypes[$extension];
            }

            if (!filesize($filename)) {
                return 'inode/x-empty';
            }

            return 'application/octet-stream';
        }

        throw new DetectionFailedException('No extension found in filename "' . $filename . '"');
    }
}
