<?php
/**
 * phlexible
 *
 * @copyright 2007-2013 brainbits GmbH (http://www.brainbits.net)
 * @license   proprietary
 */

namespace Phlexible\Bundle\MediaCacheBundle\Queue;

use Doctrine\Common\Collections\ArrayCollection;
use Phlexible\Bundle\MediaCacheBundle\Entity\QueueItem;

/**
 * Queue holds all queue items generated by a batch.
 *
 * @author Stephan Wentz <sw@brainbits.net>
 */
class Queue implements \Countable
{
    /**
     * @var QueueItem[]|ArrayCollection
     */
    private $items;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    /**
     * @param QueueItem $item
     *
     * @return $this
     */
    public function add(QueueItem $item)
    {
        if (!$this->items->contains($item)) {
            $this->items->add($item);
        }

        return $this;
    }

    /**
     * @param QueueItem $item
     *
     * @return $this
     */
    public function remove(QueueItem $item)
    {
        if ($this->items->contains($item)) {
            $this->items->removeElement($item);
        }

        return $this;
    }

    /**
     * @return QueueItem[]
     */
    public function all()
    {
        return $this->items->getValues();
    }

    /**
     * @param Queue $queue
     *
     * @return $this
     */
    public function merge(Queue $queue)
    {
        foreach ($queue->all() as $queueItem) {
            $this->add($queueItem);
        }

        return $this;
    }

    /**
     * @return int
     */
    public function count()
    {
        return $this->items->count();
    }
}
