services:
    phlexible_media_cache.worker:
        class: Phlexible\Component\MediaCache\Worker\DelegatingWorker
        public: false
        arguments:
            - "@phlexible_media_cache.worker_resolver"

    phlexible_media_cache.worker_resolver:
        class: Phlexible\Component\MediaCache\Worker\WorkerResolver
        public: false
        arguments: [[]]

    # workers
    phlexible_media_cache.worker.image:
        class: Phlexible\Component\MediaCache\Worker\ImageWorker
        public: false
        arguments:
            - "@phlexible_media_cache.storage_manager"
            - "@phlexible_media_extractor.transmutor"
            - "@phlexible_media_cache.cache_manager"
            - "@phlexible_media_type.media_type_manager"
            - "@phlexible_media_template.applier.image"
            - "@logger"
            - "%phlexible_media_cache.temp_dir%"
        tags:
            - {name: phlexible_media_cache.worker, priority: 100}
            - {name: monolog.logger, channel: media_cache}

    phlexible_media_cache.worker.null:
        class: Phlexible\Component\MediaCache\Worker\NullWorker
        public: false
        arguments:
            - "@phlexible_media_cache.cache_manager"
            - "@logger"
        tags:
            - {name: phlexible_media_cache.worker, priority: -900}
            - {name: monolog.logger, channel: media_cache}
