services:
    phlexible_media_extractor.audio_extractor.raw_audio:
        class: Phlexible\Component\MediaExtractor\AudioExtractor\RawAudioExtractor
        public: false
        tags:
            - {name: phlexible_media_extractor.extractor}
