services:
    phlexible_media_extractor.flash_extractor.raw_flash:
        class: Phlexible\Component\MediaExtractor\FlashExtractor\RawFlashExtractor
        public: false
        tags:
            - {name: phlexible_media_extractor.extractor}
