services:
    phlexible_media_extractor.video_extractor.raw_video:
        class: Phlexible\Component\MediaExtractor\VideoExtractor\RawVideoExtractor
        public: false
        tags:
            - {name: phlexible_media_extractor.extractor}
