services:
    phlexible_elementtype.elementtype_service:
        class: Phlexible\Bundle\ElementtypeBundle\ElementtypeService
        arguments:
            - "@phlexible_elementtype.elementtype_manager"
            - "@phlexible_elementtype.viability_manager"
            - "@phlexible_elementtype.usage_manager"

    phlexible_elementtype.select_field_providers:
        class: Phlexible\Bundle\ElementtypeBundle\SelectFieldProvider\SelectFieldProviderCollection
        arguments: [[]]

    phlexible_elementtype.tree_saver:
        class: Phlexible\Bundle\ElementtypeBundle\Controller\Tree\TreeSaver
        arguments:
            - "@phlexible_elementtype.elementtype_service"

    phlexible_elementtype.usage_manager:
        class: Phlexible\Bundle\ElementtypeBundle\Usage\UsageManager
        arguments:
            - "@event_dispatcher"

    # event listeners
    phlexible_elementtype.listener.get_config:
        class: Phlexible\Bundle\ElementtypeBundle\EventListener\GetConfigListener
        arguments:
            - "%phlexible_elementtype.field.suggest.seperator%"
        tags:
            - {name: kernel.event_listener, event: phlexible_gui.get_config, method: onGetConfig}

    phlexible_elementtype.listener.elementtype_usage:
        class: Phlexible\Bundle\ElementtypeBundle\EventListener\ElementtypeUsageListener
        arguments:
            - "@phlexible_elementtype.elementtype_service"
            - "@phlexible_elementtype.viability_manager"
        tags:
            - {name: kernel.event_listener, event: phlexible_elementtype.usage, method: onElementtypeUsage}

    # role providers
    phlexible_elementtype.role_provider:
        class: Phlexible\Bundle\ElementtypeBundle\RoleProvider\ElementtypeRoleProvider
        public: false
        tags:
            - {name: phlexible_gui.role_provider}
